version: '3'
services:
  csvserver:
    image: infracloudio/csvserver
    env_file:
      - csvserver.env
    environment:
      - CSVSERVER_BORDER=${CSVSERVER_BORDER}
      - CSVSERVER_LISTEN_ADDRESS=${CSVSERVER_LISTEN_ADDRESS}
      - CSVSERVER_PORT=${CSVSERVER_PORT}  
    ports:
      - "9300:9393"
    volumes:
      - type: bind
        source: ./inputFile
        target: /csvserver/inputdata
    networks:
      - csvserver-net

volumes:
  csvserver-data:

networks:
  csvserver-net:
    driver: bridge
